In [12]:
import gspread
import pandas as pd
import openpyxl
import datetime

In [13]:
gc = gspread.oauth()
sh = gc.open("Associate: Ashar Saleem")
print(sh)
spreadsheet_data = gc.export(sh.id,gspread.utils.ExportFormat.CSV)
print("Excel created")

FILE_NAME = "FILES/Dashboard.csv"
SHEET = ""
FULLNAME = "Ashar Saleem"

# Write the binary data to a file
with open(FILE_NAME, 'wb') as file:
    file.write(spreadsheet_data)

<Spreadsheet 'Associate: Ashar Saleem' id:1ASWbNa3Yd0q4vac-0_i3vupPcfgVOMUM5hAKOHjgHeY>
Excel created

In [14]:
df_new = pd.read_csv("FILES/Dashboard.csv", parse_dates=['signup_date'])
print(df_new.shape)
df_new = df_new.drop_duplicates(keep= "first", subset = "_id")
print(df_new.shape)
df_new.head()

(452, 37)
(391, 37)

,_id,full_name,signup_date,referrer_name,application,title,name,onboardingstep,aboutme1,profileheadline,...,gender,photo,phone_number,languages,secondaryemail,whatsappnumber,interested_in,is_visa_required,salary_range,Profile Completion %
0,652ab1f89f4450001d56ccb5,Shivoo Mousa,2023-10-14,NaN,Not applied,NaN,NaN,9.0,Yes,NaN,...,NaN,NaN,Yes,NaN,Yes,NaN,Yes,Yes,Yes,100.00%
1,64a297db1b4a4b001d1f7b45,Lamia Boudjellel,2023-07-03,NaN,applied,Sales Agent,Empire Heights Properties,9.0,NaN,NaN,...,Yes,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Yes,41.67%
2,649962b7508a29001dc2a6bf,Syed Usama Sohail,2023-06-26,NaN,applied,Talent Acquisition Associate,Qureos,13.0,Yes,NaN,...,Yes,NaN,Yes,NaN,Yes,NaN,NaN,Yes,Yes,66.67%
8,652b58c9690ed4001dc38d98,Zahid Raza,2023-10-15,NaN,Not applied,NaN,NaN,6.0,NaN,NaN,...,NaN,NaN,Yes,NaN,NaN,Yes,NaN,NaN,NaN,33.33%
9,64ad92b35dae83001d7665e2,Arun Chachan,2023-07-11,NaN,Not applied,NaN,NaN,13.0,Yes,NaN,...,Yes,Yes,Yes,NaN,NaN,NaN,NaN,Yes,Yes,83.33%

In [15]:
# df_new['Current_Time'] = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
# df_new['Remaining Count'] = 3

df_new['ProfileCompletion'] = pd.to_numeric(df_new['Profile Completion %'].str.split('%', expand=True)[0].str.split('.', expand=True)[0])
df_new = df_new.sort_values(by=['signup_date'], axis=0, ascending=False)
df_compensation = df_new.copy()

### How many new applicants in one week span

In [16]:
today = datetime.date.today()
PreviousMonday = today - datetime.timedelta(days=today.weekday(), weeks=1)

print(str(PreviousMonday))
PreviousMonday = "2023-10-05"
print(df_new[df_new['signup_date'] >= str(PreviousMonday)].shape)
# df_new[df_new['signup_date'] >= "2023-07-26" ]
# df_new[ (df_new['signup_date'] >= "2023-07-1") & (df_new['ProfileCompletion'] == 100)] .shape
df_new.loc[:,'signup_date_same'] = df_new['signup_date']
df_new.loc[:,'application_same'] = df_new['application']
df_new = df_new[df_new['signup_date'] >= str(PreviousMonday)]

2023-10-16
(76, 38)

In [17]:

df_new2 = df_new[df_new['ProfileCompletion'] == 100].reset_index(drop=True)
# df_new2 = df_new[df_new['onboardingstep'] == 13].reset_index(drop=True)
# df_new2 = df_new[df_new['application'] == 'applied'].reset_index(drop=True)
# df_new2 = df_new[(df_new['ProfileCompletion'] == 100)  & (df_new['application'] == 'applied')] .reset_index(drop=True)
print(" ", len(df_new2))
df_new.reset_index()[:50]

  47

,index,_id,full_name,signup_date,referrer_name,application,title,name,onboardingstep,aboutme1,...,languages,secondaryemail,whatsappnumber,interested_in,is_visa_required,salary_range,Profile Completion %,ProfileCompletion,signup_date_same,application_same
0,124,6534f17cb106bb001de02d91,Madhura Samant,2023-10-22,NaN,Not applied,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.00%,0,2023-10-22,Not applied
1,260,6534ff5ce419b5001d9f3751,Ayah Abdallah,2023-10-22,NaN,applied,Business Development Executive,Dhofar Global Tr Co LLC,9.0,Yes,...,Yes,Yes,NaN,Yes,Yes,Yes,100.00%,100,2023-10-22,applied
2,417,6534c7ece419b5001d9d385b,Nazih Jardali,2023-10-22,NaN,applied,Business Development Executive,Dhofar Global Tr Co LLC,9.0,Yes,...,NaN,Yes,Yes,Yes,Yes,Yes,100.00%,100,2023-10-22,applied
3,394,6534fd49013f29001d62b968,Mohamed Omran,2023-10-22,NaN,applied,Service Advisor,Alzayani Investments,9.0,Yes,...,NaN,Yes,Yes,Yes,Yes,Yes,100.00%,100,2023-10-22,applied
4,216,6534f146013f29001d61f4d7,Sara Merza,2023-10-22,NaN,applied,Service Advisor,Alzayani Investments,9.0,Yes,...,NaN,Yes,NaN,Yes,Yes,Yes,100.00%,100,2023-10-22,applied
5,358,65340a09e419b5001d9a277f,saadli chafik,2023-10-21,NaN,Not applied,NaN,NaN,9.0,Yes,...,NaN,Yes,Yes,Yes,Yes,Yes,100.00%,100,2023-10-21,Not applied
6,258,65341850b106bb001ddb993c,Lamya Hammadi,2023-10-21,NaN,applied,Business Development Executive,Dhofar Global Tr Co LLC,9.0,Yes,...,NaN,NaN,NaN,Yes,Yes,Yes,100.00%,100,2023-10-21,applied
7,272,652c96b5af74d8001dedc932,Prince Ngwenya,2023-10-16,NaN,Not applied,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,Yes,58.33%,58,2023-10-16,Not applied
8,383,652daa456b50f0001d2675ef,Khaled Elrewainy,2023-10-16,NaN,applied,Sales Data Analyst,Qureos Recruitment,9.0,Yes,...,NaN,NaN,Yes,Yes,Yes,Yes,100.00%,100,2023-10-16,applied
9,303,652dba9d6b50f0001d26cca4,Faisal Althunyan,2023-10-16,NaN,applied,Sales Data Analyst,Qureos Recruitment,9.0,Yes,...,NaN,NaN,NaN,Yes,Yes,Yes,100.00%,100,2023-10-16,applied
10,173,652cea97a804bf001d46fb0d,Sandy Shihadeh,2023-10-16,NaN,Not applied,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.00%,0,2023-10-16,Not applied
11,22,652ce000d38cca001d769719,Ù…Ø­Ù…Ø¯ Ø§Ù„Ù…Ù†ØªØ´Ø±ÙŠ,2023-10-16,NaN,Not applied,NaN,NaN,9.0,Yes,...,NaN,NaN,Yes,Yes,Yes,Yes,100.00%,100,2023-10-16,Not applied
12,201,652bdbedd38cca001d732c0c,IKAKO NA,2023-10-15,NaN,Not applied,NaN,NaN,9.0,Yes,...,NaN,NaN,NaN,Yes,Yes,Yes,100.00%,100,2023-10-15,Not applied
13,254,652c1f85d38cca001d748592,Umer Afzal,2023-10-15,NaN,Not applied,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.00%,0,2023-10-15,Not applied
14,305,652c06f4d38cca001d743645,Falululla Saleem,2023-10-15,NaN,applied,UI Design Specialist,Puffy,9.0,Yes,...,NaN,NaN,NaN,Yes,Yes,Yes,100.00%,100,2023-10-15,applied
15,441,652c422daf74d8001ded7493,Aliya Zeynalova,2023-10-15,NaN,Not applied,NaN,NaN,6.0,NaN,...,NaN,NaN,NaN,NaN,NaN,Yes,41.67%,41,2023-10-15,Not applied
16,8,652b58c9690ed4001dc38d98,Zahid Raza,2023-10-15,NaN,Not applied,NaN,NaN,6.0,NaN,...,NaN,NaN,Yes,NaN,NaN,NaN,33.33%,33,2023-10-15,Not applied
17,58,652af0c8af74d8001de6d8ce,Barakat Bawzeer,2023-10-14,NaN,applied,Sales Data Analyst,Qureos Recruitment,9.0,Yes,...,NaN,NaN,Yes,Yes,Yes,Yes,100.00%,100,2023-10-14,applied
18,222,652ae72bd38cca001d6f3369,Shwetha Shaji,2023-10-14,NaN,applied,UI Design Specialist,Puffy,9.0,Yes,...,NaN,Yes,NaN,Yes,Yes,Yes,100.00%,100,2023-10-14,applied
19,404,652af8dd690ed4001dc23142,mohamed alaa,2023-10-14,NaN,Not applied,NaN,NaN,5.0,NaN,...,NaN,Yes,NaN,NaN,NaN,NaN,25.00%,25,2023-10-14,Not applied
20,332,652ab1f0af74d8001de4a508,Badai Aldahhasi,2023-10-14,NaN,applied,Sales Data Analyst,Qureos Recruitment,9.0,Yes,...,Yes,NaN,NaN,Yes,Yes,Yes,100.00%,100,2023-10-14,applied
21,86,652acc14af74d8001de5fc0b,Nasir Mahmood,2023-10-14,NaN,Not applied,NaN,NaN,5.0,NaN,...,NaN,NaN,Yes,NaN,NaN,Yes,33.33%,33,2023-10-14,Not applied
22,389,652ac7779f4450001d57eff7,Abde nnasser Mehamedia,2023-10-14,NaN,applied,UI Design Specialist,Puffy,9.0,Yes,...,NaN,NaN,NaN,Yes,Yes,Yes,100.00%,100,2023-10-14,applied
23,121,652aa880d38cca001d6d5dd5,Ahmed Yasser,2023-10-14,NaN,applied,Sales Data Analyst,Qureos Recruitment,9.0,Yes,...,NaN,Yes,Yes,Yes,Yes,Yes,100.00%,100,2023-10-14,applied
24,0,652ab1f89f4450001d56ccb5,Shivoo Mousa,2023-10-14,NaN,Not applied,NaN,NaN,9.0,Yes,...,NaN,Yes,NaN,Yes,Yes,Yes,100.00%,100,2023-10-14,Not applied
25,291,652ab377af74d8001de4ca2e,Ahmed Alrabiah,2023-10-14,NaN,applied,Sales Data Analyst,Qureos Recruitment,9.0,Yes,...,NaN,Yes,NaN,Yes,Yes,Yes,100.00%,100,2023-10-14,applied
26,56,652ab1b0af74d8001de4a452,Mohamed Yoosuf Shajith,2023-10-14,NaN,applied,Sales Data Analyst,Qureos Recruitment,9.0,Yes,...,NaN,NaN,Yes,Yes,Yes,Yes,100.00%,100,2023-10-14,applied
27,11,652ad892af74d8001de649a0,Ahmed Alawami,2023-10-14,NaN,applied,Sales Data Analyst,Qureos Recruitment,9.0,Yes,...,NaN,NaN,NaN,Yes,Yes,Yes,100.00%,100,2023-10-14,applied
28,398,652ab32ad38cca001d6d98e9,Osama Bawazir,2023-10-14,NaN,applied,Sales Data Analyst,Qureos Recruitment,9.0,Yes,...,NaN,Yes,Yes,Yes,Yes,Yes,100.00%,100,2023-10-14,applied
29,143,652ab65ad38cca001d6dbe16,Alaa Alkees,2023-10-14,NaN,applied,Sales Data Analyst,Qureos Recruitment,9.0,Yes,...,NaN,NaN,Yes,Yes,Yes,Yes,100.00%,100,2023-10-14,applied
30,175,652ab4c0af74d8001de4def6,Altaf Ur Rehman Mohammed,2023-10-14,NaN,applied,Sales Data Analyst,Qureos Recruitment,9.0,Yes,...,NaN,NaN,NaN,Yes,Yes,Yes,100.00%,100,2023-10-14,applied
31,241,652ab495d38cca001d6da17d,Ohood Awad,2023-10-14,NaN,Not applied,NaN,NaN,9.0,Yes,...,NaN,Yes,Yes,Yes,Yes,Yes,100.00%,100,2023-10-14,Not applied
32,278,6526628a09d457001d4afb18,usha Bashera,2023-10-11,NaN,Not applied,NaN,NaN,9.0,Yes,...,NaN,Yes,Yes,Yes,Yes,Yes,100.00%,100,2023-10-11,Not applied
33,220,65250b6d201088001d7603bc,Karen Nassour,2023-10-10,NaN,applied,Executive Assistant,Qureos Recruitment,9.0,Yes,...,NaN,Yes,Yes,Yes,Yes,Yes,100.00%,100,2023-10-10,applied
34,48,6523df386dcc31001df47a3b,Sehar Malik,2023-10-09,NaN,Not applied,NaN,NaN,9.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,41.67%,41,2023-10-09,Not applied
35,325,652382624310a5001c61747d,Kinga Kuruczova,2023-10-09,NaN,Not applied,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.00%,0,2023-10-09,Not applied
36,24,652350a5316410001dc4a4f1,Umar Saleemi,2023-10-09,NaN,applied,Accountant Assistant,Dhofar Global Tr Co LLC,9.0,Yes,...,NaN,Yes,Yes,Yes,Yes,Yes,100.00%,100,2023-10-09,applied
37,376,65239819fd4ab8001dd3f58a,petrina pinto,2023-10-09,NaN,applied,Executive Assistant,Qureos Recruitment,9.0,Yes,...,NaN,Yes,Yes,Yes,Yes,Yes,100.00%,100,2023-10-09,applied
38,223,6522e83dbc9d8c001d094865,Jino Abraham,2023-10-08,NaN,Not applied,NaN,NaN,7.0,NaN,...,NaN,Yes,NaN,NaN,NaN,NaN,41.67%,41,2023-10-08,Not applied
39,296,65230399708bff001e716064,Jumana Al Abri,2023-10-08,NaN,Not applied,NaN,NaN,9.0,Yes,...,NaN,NaN,NaN,Yes,Yes,Yes,100.00%,100,2023-10-08,Not applied
40,240,65225d14f5f1bd001dfdb1aa,Sujin M Jinna,2023-10-08,NaN,Not applied,NaN,NaN,9.0,Yes,...,NaN,NaN,Yes,Yes,Yes,Yes,100.00%,100,2023-10-08,Not applied
41,118,65228ccfda9190001db197ea,Ayesha Samreen,2023-10-08,NaN,Not applied,NaN,NaN,9.0,Yes,...,NaN,NaN,NaN,Yes,NaN,Yes,100.00%,100,2023-10-08,Not applied
42,326,652287b8880df1001e430223,Muhammad Umer Baig,2023-10-08,NaN,Not applied,NaN,NaN,7.0,NaN,...,NaN,Yes,Yes,NaN,NaN,NaN,33.33%,33,2023-10-08,Not applied
43,295,65222f4099106b001db142ae,Maitha Albalushi,2023-10-08,NaN,Not applied,NaN,NaN,6.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,25.00%,25,2023-10-08,Not applied
44,158,652274aec52cda001d49479f,AlMukhtar AlKhaifi,2023-10-08,NaN,applied,Accountant Assistant,Dhofar Global Tr Co LLC,9.0,Yes,...,NaN,Yes,Yes,Yes,NaN,Yes,100.00%,100,2023-10-08,applied
45,104,65222e17068ba9001d415821,Dilona Mendonca,2023-10-08,NaN,Not applied,NaN,NaN,7.0,NaN,...,NaN,Yes,NaN,NaN,NaN,Yes,41.67%,41,2023-10-08,Not applied
46,402,652283e5f83248001ca53100,Ruqaia Alomairi,2023-10-08,NaN,applied,Accountant Assistant,Dhofar Global Tr Co LLC,9.0,NaN,...,NaN,NaN,NaN,NaN,NaN,Yes,58.33%,58,2023-10-08,applied
47,19,652283da7ee91f001de5e885,tarek awad,2023-10-08,NaN,Not applied,NaN,NaN,9.0,Yes,...,NaN,Yes,Yes,Yes,Yes,Yes,100.00%,100,2023-10-08,Not applied
48,49,652266c20f2030001dabab24,sarika tamang,2023-10-08,NaN,Not applied,NaN,NaN,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.00%,0,2023-10-08,Not applied
49,200,6521a040316410001dc36685,Afreen Shaikh,2023-10-07,NaN,applied,Executive Assistant,Qureos Recruitment,9.0,Yes,...,NaN,NaN,NaN,NaN,NaN,Yes,66.67%,66,2023-10-07,applied

In [18]:
PreviousMonth = "2023-08-01"
CurrentMonth = "2023-09-03"

df_compensation = df_compensation[ (df_compensation['signup_date'] >= PreviousMonth) & (df_compensation['signup_date'] <= CurrentMonth)]
df_compensation.shape

(71, 38)

In [19]:
df_compensation2 = df_compensation[df_compensation['ProfileCompletion'] == 100].reset_index(drop=True)
print(len(df_compensation2))
# df_compensation.to_csv('AllApplicants_NoDuplicates___from_1thAug_to_5thSept.csv')
# df_compensation2.to_csv('CompletedApplicants_NoDuplicates___from_1thAug_to_5thSept.csv')
df_compensation2.reset_index()

44

,index,_id,full_name,signup_date,referrer_name,application,title,name,onboardingstep,aboutme1,...,photo,phone_number,languages,secondaryemail,whatsappnumber,interested_in,is_visa_required,salary_range,Profile Completion %,ProfileCompletion
0,0,64f40a60455d6e001dfe77c5,Rajesh Raghav,2023-09-03,NaN,applied,IT Coordinator,Alzayani Investments,9.0,Yes,...,NaN,Yes,NaN,NaN,NaN,Yes,Yes,Yes,100.00%,100
1,1,64f34d6a675141001d126e8f,Dhinesh Natarajan,2023-09-02,NaN,applied,Market Intelligence Manager,Dhofar Global Tr Co LLC,9.0,Yes,...,NaN,Yes,NaN,Yes,Yes,Yes,Yes,Yes,100.00%,100
2,2,64f1ba394979d4001df69520,Owais Abid,2023-09-01,NaN,applied,IT Coordinator,Alzayani Investments,9.0,Yes,...,NaN,Yes,NaN,NaN,NaN,Yes,Yes,Yes,100.00%,100
3,3,64f203c9675141001d109f86,Sufaid Muhammed,2023-09-01,NaN,Not applied,NaN,NaN,9.0,Yes,...,NaN,Yes,NaN,NaN,NaN,Yes,Yes,Yes,100.00%,100
4,4,64f1b4461b2139001ddd2ecc,Toqeer Nasir,2023-09-01,NaN,applied,IT Coordinator,Alzayani Investments,9.0,Yes,...,NaN,Yes,NaN,Yes,Yes,Yes,Yes,Yes,100.00%,100
5,5,64f1b5a5104070001d29b361,saiyyedali saiyyed,2023-09-01,NaN,applied,Solutions Delivery Manager,Persistence Recruitment,9.0,Yes,...,Yes,Yes,NaN,NaN,Yes,Yes,Yes,Yes,100.00%,100
6,6,64f1b08356920d001efbab7c,M. Ahsan Akmal,2023-09-01,NaN,applied,IT Coordinator,Alzayani Investments,9.0,Yes,...,NaN,Yes,NaN,NaN,Yes,Yes,Yes,Yes,100.00%,100
7,7,64f1b5c8d0059f001d2db7c2,Jassim Ali,2023-09-01,NaN,applied,Accountant,Alzayani Investments,9.0,Yes,...,NaN,Yes,NaN,NaN,Yes,Yes,Yes,Yes,100.00%,100
8,8,64f1b0721314ec001de097b1,Mohammed Ali,2023-09-01,NaN,Not applied,NaN,NaN,9.0,Yes,...,NaN,Yes,NaN,NaN,Yes,Yes,Yes,Yes,100.00%,100
9,9,64f1ed62104070001d2ab1db,Qasim Javed,2023-09-01,NaN,applied,Sales Data Analyst,Qureos Recruitment,9.0,Yes,...,NaN,Yes,NaN,Yes,Yes,Yes,Yes,Yes,100.00%,100
10,10,64f211f714967f001d05be6f,Mohammed Al Marzooq,2023-09-01,NaN,Not applied,NaN,NaN,9.0,Yes,...,NaN,Yes,NaN,Yes,Yes,Yes,Yes,Yes,100.00%,100
11,11,64f1eac9956739001ddc70df,Bilal Alghoch,2023-09-01,NaN,applied,IT Coordinator,Alzayani Investments,9.0,Yes,...,NaN,Yes,NaN,NaN,NaN,Yes,Yes,Yes,100.00%,100
12,12,64f1bc8f88fcf0001d6e0dc7,Priyal Dharne,2023-09-01,NaN,applied,Market Intelligence Manager,Dhofar Global Tr Co LLC,9.0,Yes,...,NaN,Yes,NaN,Yes,Yes,Yes,Yes,Yes,100.00%,100
13,13,64f1d5d91b2139001dddb48a,Muhammad Khurram Shahbaz,2023-09-01,NaN,applied,Market Intelligence Manager,Dhofar Global Tr Co LLC,9.0,Yes,...,NaN,Yes,NaN,NaN,Yes,Yes,Yes,Yes,100.00%,100
14,14,64f1ca361b2139001ddd94dc,Amr Hussain,2023-09-01,NaN,Not applied,NaN,NaN,9.0,Yes,...,NaN,Yes,NaN,NaN,Yes,Yes,Yes,Yes,100.00%,100
15,15,64e849129f86b9001db97932,FAWAD AHMAD,2023-08-25,NaN,Not applied,NaN,NaN,9.0,Yes,...,Yes,Yes,NaN,Yes,Yes,Yes,Yes,Yes,100.00%,100
16,16,64e932c174082b001efec5b2,Mahmoud Ali,2023-08-25,NaN,Not applied,NaN,NaN,9.0,Yes,...,NaN,Yes,NaN,NaN,Yes,Yes,Yes,Yes,100.00%,100
17,17,64e6f377116795001dbcb11d,Alaa Diab,2023-08-24,NaN,applied,Business Development Executive,Dhofar Global Tr Co LLC,9.0,Yes,...,NaN,Yes,NaN,Yes,Yes,Yes,Yes,Yes,100.00%,100
18,18,64e75df2e63006001d54a834,Ali Gujjer,2023-08-24,NaN,Not applied,NaN,NaN,9.0,Yes,...,NaN,Yes,NaN,Yes,NaN,Yes,Yes,Yes,100.00%,100
19,19,64e72444c5a562001cabbb77,Abdul Rahman Sinan,2023-08-24,NaN,Not applied,NaN,NaN,9.0,Yes,...,NaN,Yes,NaN,Yes,Yes,Yes,Yes,Yes,100.00%,100
20,20,64e61c4c9f86b9001db49519,Ayesha Kanwal,2023-08-23,NaN,applied,Motion Designer & Graphic Designer,Vague,9.0,Yes,...,NaN,Yes,NaN,Yes,Yes,Yes,Yes,Yes,100.00%,100
21,21,64e614979f86b9001db48d76,Zamzam Al-Hinai,2023-08-23,NaN,applied,Business Development Executive,Dhofar Global Tr Co LLC,9.0,Yes,...,NaN,Yes,NaN,Yes,NaN,Yes,Yes,Yes,100.00%,100
22,22,64e64ed2116795001dbba6b5,Abdallah Al Harthi,2023-08-23,NaN,applied,Business Development Executive,Dhofar Global Tr Co LLC,9.0,Yes,...,NaN,Yes,NaN,NaN,NaN,Yes,Yes,Yes,100.00%,100
23,23,64e6196a1a143b001cc0eaa8,Khawaja Adeel,2023-08-23,NaN,applied,Business Development Manager,Qureos,9.0,Yes,...,NaN,Yes,NaN,NaN,NaN,Yes,Yes,Yes,100.00%,100
24,24,64e66bf5ee5b89001d447fd5,Thouseef Pk,2023-08-23,NaN,applied,Business Development Executive,Dhofar Global Tr Co LLC,9.0,Yes,...,NaN,Yes,NaN,Yes,Yes,Yes,Yes,Yes,100.00%,100
25,25,64e61becaed0ea001d954a1c,PRAJEESH NK,2023-08-23,NaN,applied,Business Development Executive,Dhofar Global Tr Co LLC,9.0,Yes,...,NaN,Yes,NaN,NaN,NaN,Yes,Yes,Yes,100.00%,100
26,26,64e64cb1116795001dbba647,Alaa Abutaleb,2023-08-23,NaN,applied,Business Development Executive,Dhofar Global Tr Co LLC,9.0,Yes,...,NaN,Yes,NaN,NaN,NaN,Yes,Yes,Yes,100.00%,100
27,27,64e651f2116795001dbba82b,Danish Ansari,2023-08-23,NaN,applied,Business Development Executive,Dhofar Global Tr Co LLC,9.0,Yes,...,NaN,Yes,NaN,NaN,NaN,Yes,Yes,Yes,100.00%,100
28,28,64de23b3247256001d5a51ef,waqar hyder,2023-08-17,NaN,Not applied,NaN,NaN,9.0,Yes,...,NaN,Yes,NaN,Yes,Yes,Yes,Yes,Yes,100.00%,100
29,29,64de44ffd8b476001db1114b,Mohammad karbala,2023-08-17,NaN,applied,Sales Specialist,Empire Heights Properties,9.0,Yes,...,NaN,Yes,NaN,NaN,Yes,Yes,Yes,Yes,100.00%,100
30,30,64dc4260523152001e0ec5d6,Ahmed Samy,2023-08-16,NaN,applied,Corporate Sales Engineer,Sahara Net Co.,9.0,Yes,...,NaN,Yes,NaN,Yes,Yes,Yes,Yes,Yes,100.00%,100
31,31,64dc6966862274001de427ca,fady Samy,2023-08-16,NaN,Not applied,NaN,NaN,9.0,Yes,...,NaN,Yes,NaN,NaN,NaN,Yes,Yes,Yes,100.00%,100
32,32,64dc915a862274001de55897,Sylvester Sameer,2023-08-16,NaN,applied,Sales Specialist,Empire Heights Properties,9.0,Yes,...,NaN,Yes,NaN,NaN,NaN,Yes,Yes,Yes,100.00%,100
33,33,64dc6e7b4408b7001d28c1f2,Mithula Nair,2023-08-16,NaN,applied,Sales Specialist,Empire Heights Properties,9.0,Yes,...,NaN,Yes,NaN,NaN,Yes,Yes,Yes,Yes,100.00%,100
34,34,64dc395fd04e72001d54fe5b,Sadique Muqammal Haque,2023-08-16,NaN,applied,Sales Specialist,Empire Heights Properties,9.0,Yes,...,NaN,Yes,NaN,NaN,Yes,Yes,Yes,Yes,100.00%,100
35,35,64dc58f0523152001e0ee1e5,Noor ul Hassan,2023-08-16,NaN,applied,Sales Specialist,Empire Heights Properties,9.0,Yes,...,NaN,Yes,NaN,NaN,Yes,Yes,Yes,Yes,100.00%,100
36,36,64dc6b74d04e72001d55b680,Krunal Parikh,2023-08-16,NaN,applied,Sales Specialist,Empire Heights Properties,9.0,Yes,...,NaN,Yes,NaN,NaN,Yes,Yes,Yes,Yes,100.00%,100
37,37,64d2b63052fa8d001d8f5ea1,Haidar Alsalem,2023-08-08,NaN,Not applied,NaN,NaN,9.0,Yes,...,NaN,Yes,NaN,NaN,NaN,Yes,Yes,Yes,100.00%,100
38,38,64ce685ea0ddd8001d59c45a,Fatimah Sami,2023-08-05,NaN,Not applied,NaN,NaN,9.0,Yes,...,NaN,Yes,NaN,Yes,NaN,Yes,Yes,Yes,100.00%,100
39,39,64cdfde3bff6d3001d1aa439,Elissar Mashtoub,2023-08-05,NaN,applied,Marketing Manager,ReThinkHR Solutions,9.0,Yes,...,NaN,Yes,NaN,Yes,Yes,Yes,Yes,Yes,100.00%,100
40,40,64ce1e53bff6d3001d1cc63a,Sherif Sameh,2023-08-05,NaN,applied,Cloud Solutions Engineer,Sahara Net Co.,9.0,Yes,...,NaN,Yes,NaN,NaN,NaN,Yes,Yes,Yes,100.00%,100
41,41,64cd2e7d544588001d5abb1a,Nada Alhussaini,2023-08-04,NaN,applied,Marketing Manager,ReThinkHR Solutions,9.0,Yes,...,NaN,Yes,NaN,NaN,NaN,Yes,Yes,Yes,100.00%,100
42,42,64cd21c279373e001de618ba,Daniece Luckey,2023-08-04,NaN,applied,Marketing Manager,ReThinkHR Solutions,9.0,Yes,...,NaN,Yes,NaN,NaN,NaN,Yes,Yes,Yes,100.00%,100
43,43,64cd5334544588001d5c3b38,Hossain Albasha,2023-08-04,NaN,Not applied,NaN,NaN,9.0,Yes,...,NaN,Yes,Yes,NaN,NaN,Yes,Yes,Yes,100.00%,100

In [20]:
# df_new.to_csv("FILES/Applicants_new.csv", index = False)

In [21]:
# df_old = pd.read_csv("FILES/Applicants_old.csv")
# df_new = pd.read_csv("FILES/Applicants_new.csv")

In [22]:
""""
updated_records = []

for index, row_old in df_old.iterrows():
    _id = row_old["_id"]

    if _id in df_new["_id"].values:
        row_new = df_new[df_new["_id"] == _id].iloc[0]
        
#         # Extract desired columns from df_new
        profile_completion_percent = row_new["Profile Completion %"]
        profile_completion = row_new["ProfileCompletion"]
        
#         # Update the relevant columns in the old row
        row_old["Profile Completion %"] = profile_completion_percent
        row_old["ProfileCompletion"] = profile_completion
    
    # Append the updated row to the list
    updated_records.append(row_old)

updated_df = pd.concat(updated_records, axis=1).T

# Export updated dataframe as CSV
updated_df.to_csv("FILES/Applicants_old.csv", index=False)
updated_df
"""

'"\nupdated_records = []\n\nfor index, row_old in df_old.iterrows():\n    _id = row_old["_id"]\n\n    if _id in df_new["_id"].values:\n        row_new = df_new[df_new["_id"] == _id].iloc[0]\n        \n#         # Extract desired columns from df_new\n        profile_completion_percent = row_new["Profile Completion %"]\n        profile_completion = row_new["ProfileCompletion"]\n        \n#         # Update the relevant columns in the old row\n        row_old["Profile Completion %"] = profile_completion_percent\n        row_old["ProfileCompletion"] = profile_completion\n    \n    # Append the updated row to the list\n    updated_records.append(row_old)\n\nupdated_df = pd.concat(updated_records, axis=1).T\n\n# Export updated dataframe as CSV\nupdated_df.to_csv("FILES/Applicants_old.csv", index=False)\nupdated_df\n'