In [21]:
import gspread
import pandas as pd
import openpyxl
import datetime

In [22]:
gc = gspread.oauth()
sh = gc.open("Associate: Ashar Saleem")
print(sh)
spreadsheet_data = gc.export(sh.id,gspread.utils.ExportFormat.CSV)
print("Excel created")

FILE_NAME = "FILES/Dashboard.csv"
SHEET = ""
FULLNAME = "Ashar Saleem"

# Write the binary data to a file
with open(FILE_NAME, 'wb') as file:
    file.write(spreadsheet_data)

<Spreadsheet 'Associate: Ashar Saleem' id:1ASWbNa3Yd0q4vac-0_i3vupPcfgVOMUM5hAKOHjgHeY>
Excel created

In [23]:
df_new = pd.read_csv("FILES/Dashboard.csv", parse_dates=['signup_date'])
print(df_new.shape)
df_new = df_new.drop_duplicates(keep= "first", subset = "_id")
print(df_new.shape)
df_new.head()

(362, 37)
(313, 37)

,_id,full_name,signup_date,referrer_name,application,title,name,onboardingstep,aboutme1,profileheadline,...,gender,photo,phone_number,languages,secondaryemail,whatsappnumber,interested_in,is_visa_required,salary_range,Profile Completion %
0,64ad91135dae83001d765ccd,Srihar Rathor,2023-07-11,NaN,Not applied,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00%
1,64a2df48be4ec3001df431cb,adnan ktr,2023-07-03,NaN,applied,Experienced UI/UX Designer,Ideofuzion (Pvt.) Ltd.,9.0,NaN,NaN,...,NaN,NaN,Yes,NaN,NaN,Yes,NaN,NaN,NaN,50.00%
2,64ae368ea83447001dfadc2c,SSD NA,2023-07-12,NaN,Not applied,NaN,NaN,13.0,Yes,NaN,...,Yes,Yes,Yes,NaN,NaN,NaN,NaN,Yes,Yes,83.33%
3,64997f041b4a4b001df78f83,Saad Faisal,2023-06-26,NaN,applied,Business Development Executive,The Brand Consultants,13.0,Yes,NaN,...,Yes,Yes,Yes,NaN,NaN,NaN,NaN,Yes,NaN,75.00%
4,649973f438dc80001d120414,Asif Ali,2023-06-26,NaN,applied,Customer Success Lead,Qureos,13.0,NaN,NaN,...,Yes,Yes,Yes,NaN,Yes,Yes,NaN,Yes,NaN,50.00%

In [24]:
# df_new['Current_Time'] = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
# df_new['Remaining Count'] = 3

df_new['ProfileCompletion'] = pd.to_numeric(df_new['Profile Completion %'].str.split('%', expand=True)[0].str.split('.', expand=True)[0])
df_new = df_new.sort_values(by=['signup_date'], axis=0, ascending=False)

### How many new applicants in one week span

In [25]:
today = datetime.date.today()
PreviousMonday = today - datetime.timedelta(days=today.weekday(), weeks=1)

print(str(PreviousMonday))
PreviousMonday = "2023-09-01"
print(df_new[df_new['signup_date'] >= str(PreviousMonday)].shape)
# df_new[df_new['signup_date'] >= "2023-07-26" ]
# df_new[ (df_new['signup_date'] >= "2023-07-1") & (df_new['ProfileCompletion'] == 100)] .shape
df_new.loc[:,'signup_date_same'] = df_new['signup_date']
df_new.loc[:,'application_same'] = df_new['application']
df_new = df_new[df_new['signup_date'] >= str(PreviousMonday)]

2023-09-25
(85, 38)

In [26]:

df_new2 = df_new[df_new['ProfileCompletion'] == 100].reset_index(drop=True)
# df_new2 = df_new[df_new['onboardingstep'] == 13].reset_index(drop=True)
# df_new2 = df_new[df_new['application'] == 'applied'].reset_index(drop=True)
# df_new2 = df_new[(df_new['ProfileCompletion'] == 100)  & (df_new['application'] == 'applied')] .reset_index(drop=True)
print("After -3:", len(df_new2)-3)
df_new.reset_index()[:40]

After -3: 57

,index,_id,full_name,signup_date,referrer_name,application,title,name,onboardingstep,aboutme1,...,languages,secondaryemail,whatsappnumber,interested_in,is_visa_required,salary_range,Profile Completion %,ProfileCompletion,signup_date_same,application_same
0,97,651b5c2679d97a001df8c34e,Tharshoom Sait,2023-10-03,NaN,Not applied,NaN,NaN,1.0,NaN,...,NaN,NaN,Yes,NaN,NaN,NaN,41.67%,41,2023-10-03,Not applied
1,34,651bc6e0da979d001cf20216,Abdulrahman Abouaid,2023-10-03,NaN,applied,Business Development Executive,Dhofar Global Tr Co LLC,9.0,Yes,...,NaN,NaN,Yes,NaN,NaN,NaN,58.33%,58,2023-10-03,applied
2,51,651a6a97338042001db23b20,Mithilesh Kumar,2023-10-02,NaN,applied,Business Development Executive,Dhofar Global Tr Co LLC,9.0,NaN,...,NaN,NaN,NaN,NaN,NaN,Yes,58.33%,58,2023-10-02,applied
3,231,651a9ea8fb3859001df183e9,Mohannad Mohamed,2023-10-02,NaN,Not applied,NaN,NaN,2.0,NaN,...,NaN,Yes,Yes,NaN,NaN,NaN,50.00%,50,2023-10-02,Not applied
4,239,651a83ab3a6968001d3bc5a0,Aquib Dalwai,2023-10-02,NaN,Not applied,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.00%,0,2023-10-02,Not applied
5,14,651a86c56bf12a001ddfd563,Ahmad Dalanny,2023-10-02,NaN,Not applied,NaN,NaN,6.0,NaN,...,NaN,Yes,Yes,NaN,NaN,Yes,41.67%,41,2023-10-02,Not applied
6,66,65196c1960cf23001d0ffba2,Shoukath Mohammed,2023-10-01,NaN,applied,Accountant Assistant,Qureos Recruitment,9.0,Yes,...,NaN,NaN,NaN,Yes,Yes,Yes,100.00%,100,2023-10-01,applied
7,304,65198dcc501eca001d3209ed,Meera Sahib,2023-10-01,NaN,applied,Accountant,Alzayani Investments,9.0,Yes,...,NaN,Yes,NaN,NaN,NaN,NaN,58.33%,58,2023-10-01,applied
8,112,6518db0fc02bbc001dca4a58,Shubham Singh,2023-10-01,NaN,applied,Business Development Executive,Dhofar Global Tr Co LLC,9.0,Yes,...,NaN,Yes,Yes,NaN,NaN,NaN,58.33%,58,2023-10-01,applied
9,261,6518ef9c81a4ad001d5f44ca,Ranotosh Ghosh,2023-10-01,NaN,applied,Business Development Executive,Dhofar Global Tr Co LLC,9.0,Yes,...,NaN,Yes,Yes,Yes,Yes,Yes,100.00%,100,2023-10-01,applied
10,332,651957c9f7f452001d132e04,Jawad Ali Khan,2023-10-01,NaN,Not applied,NaN,NaN,9.0,Yes,...,NaN,Yes,Yes,Yes,Yes,Yes,100.00%,100,2023-10-01,Not applied
11,156,651854b72dbd11001d2bb3a5,Georjedine Jeanlouis,2023-09-30,NaN,Not applied,NaN,NaN,5.0,NaN,...,NaN,Yes,NaN,NaN,NaN,NaN,25.00%,25,2023-09-30,Not applied
12,345,65185c2b2dbd11001d2bb56d,Eslam Mohamed,2023-09-30,NaN,applied,Accountant,Alzayani Investments,9.0,Yes,...,Yes,Yes,Yes,Yes,Yes,Yes,100.00%,100,2023-09-30,applied
13,30,6518623db1da38001dcd8fb7,Yara Mhmd,2023-09-30,NaN,Not applied,NaN,NaN,9.0,NaN,...,NaN,Yes,Yes,NaN,NaN,NaN,41.67%,41,2023-09-30,Not applied
14,146,65185732519db2001d548bd9,Eslam Morsy,2023-09-30,NaN,applied,Accountant,Alzayani Investments,9.0,Yes,...,NaN,NaN,NaN,Yes,Yes,Yes,100.00%,100,2023-09-30,applied
15,344,65186692e34bdb001d3aee4e,Ashly Sara Koshy,2023-09-30,NaN,Not applied,NaN,NaN,9.0,Yes,...,NaN,Yes,NaN,Yes,NaN,Yes,100.00%,100,2023-09-30,Not applied
16,343,651885bf3689f2001d7c95c4,Sayed hassan sayed Ahmed,2023-09-30,NaN,Not applied,NaN,NaN,7.0,NaN,...,NaN,Yes,Yes,NaN,NaN,Yes,50.00%,50,2023-09-30,Not applied
17,17,651854bae2b036001ee3e874,Ahmed Abdelrazik,2023-09-30,NaN,applied,Business Development Executive,Dhofar Global Tr Co LLC,9.0,Yes,...,NaN,Yes,Yes,Yes,Yes,Yes,100.00%,100,2023-09-30,applied
18,179,651873621f6eb0001d94d1b2,Yehya Asal,2023-09-30,NaN,applied,Business Development Executive,Dhofar Global Tr Co LLC,9.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,50.00%,50,2023-09-30,applied
19,242,651857522b7065001ddaca54,Mehsab Ali e,2023-09-30,NaN,applied,Accountant,Alzayani Investments,9.0,Yes,...,NaN,NaN,Yes,Yes,Yes,Yes,100.00%,100,2023-09-30,applied
20,188,65185aaee34bdb001d3adb5a,Duha Saeed,2023-09-30,NaN,Not applied,NaN,NaN,9.0,NaN,...,NaN,Yes,NaN,NaN,NaN,NaN,50.00%,50,2023-09-30,Not applied
21,163,6518558d4f56e3001d0a2e99,Hassan Algain,2023-09-30,NaN,applied,Business Development Executive,Dhofar Global Tr Co LLC,9.0,Yes,...,NaN,Yes,Yes,Yes,Yes,Yes,100.00%,100,2023-09-30,applied
22,56,6513ecba5b38f7001d6c200d,Mohammed Bayaz,2023-09-27,NaN,applied,Draftsman,Qureos Recruitment,9.0,Yes,...,NaN,Yes,Yes,Yes,Yes,Yes,100.00%,100,2023-09-27,applied
23,95,6512ca5f881c9b001d4fec37,Safvan Vt,2023-09-26,NaN,applied,Draftsman,Qureos Recruitment,9.0,Yes,...,NaN,NaN,Yes,Yes,Yes,Yes,100.00%,100,2023-09-26,applied
24,127,651274bbef73aa001da534d3,Mohammad Bashar,2023-09-26,NaN,Not applied,NaN,NaN,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.00%,0,2023-09-26,Not applied
25,355,6511def666c03e001dbe2f73,Kartiksingh Hushare,2023-09-25,NaN,applied,Business Development Executive,Dhofar Global Tr Co LLC,9.0,Yes,...,NaN,Yes,Yes,Yes,Yes,Yes,100.00%,100,2023-09-25,applied
26,82,6511e08a4786f9001d29fc15,Edward Jerameel Martin,2023-09-25,NaN,applied,Procurement Assistant,ADEKA AL OTAIBA MIDDLE EAST,9.0,Yes,...,NaN,NaN,NaN,Yes,NaN,Yes,100.00%,100,2023-09-25,applied
27,218,65111816ebc35b001d6a123a,shafiq mohammed,2023-09-25,NaN,applied,Procurement Assistant,ADEKA AL OTAIBA MIDDLE EAST,9.0,Yes,...,NaN,Yes,NaN,Yes,Yes,Yes,100.00%,100,2023-09-25,applied
28,36,651111f79348f0001d78c621,AMALNADH NJ,2023-09-25,NaN,applied,Interior Design Draftsman,Qureos Recruitment,9.0,Yes,...,NaN,Yes,Yes,Yes,Yes,Yes,100.00%,100,2023-09-25,applied
29,120,6511d846e2772d001de51744,Alex Varghese,2023-09-25,NaN,applied,Procurement Assistant,ADEKA AL OTAIBA MIDDLE EAST,9.0,Yes,...,NaN,NaN,Yes,Yes,NaN,Yes,100.00%,100,2023-09-25,applied
30,232,650fef4ddc22bd001dee27ce,Md. Saiful islam Ropam,2023-09-24,NaN,Not applied,NaN,NaN,9.0,Yes,...,NaN,Yes,Yes,Yes,Yes,Yes,100.00%,100,2023-09-24,Not applied
31,288,650ff6303c8e50001c2005a8,Zawar Amin khan,2023-09-24,NaN,applied,Procurement Assistant,ADEKA AL OTAIBA MIDDLE EAST,9.0,Yes,...,NaN,Yes,Yes,Yes,Yes,Yes,100.00%,100,2023-09-24,applied
32,184,650fcf78781892001ddc3d2b,nabil sayyed,2023-09-24,NaN,applied,Interior Design Draftsman,Qureos Recruitment,9.0,Yes,...,NaN,Yes,NaN,Yes,Yes,Yes,100.00%,100,2023-09-24,applied
33,219,650fef799348f0001d784247,Syamlal Swarnappan,2023-09-24,NaN,applied,Procurement Assistant,ADEKA AL OTAIBA MIDDLE EAST,9.0,Yes,...,NaN,Yes,Yes,Yes,Yes,Yes,100.00%,100,2023-09-24,applied
34,172,65103b5723114b001de54884,shahbaz akhter,2023-09-24,NaN,applied,Interior Design Draftsman,Qureos Recruitment,9.0,Yes,...,NaN,Yes,NaN,Yes,Yes,Yes,100.00%,100,2023-09-24,applied
35,228,650fad23b9e90b001dbf9a0f,Muhammed Shafi,2023-09-24,NaN,Not applied,NaN,NaN,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.00%,0,2023-09-24,Not applied
36,138,650f2636a5d55e001d5b51fd,Arun Raghavan,2023-09-23,NaN,Not applied,NaN,NaN,7.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,33.33%,33,2023-09-23,Not applied
37,319,650f216f0acb7b001d9321ce,Kartik Hushare,2023-09-23,NaN,applied,Procurement Assistant,ADEKA AL OTAIBA MIDDLE EAST,9.0,Yes,...,NaN,Yes,Yes,Yes,Yes,Yes,100.00%,100,2023-09-23,applied
38,83,650f0fc1135a25001da8ca36,Rehab Tigani,2023-09-23,NaN,applied,Interior Design Draftsman,Qureos Recruitment,9.0,Yes,...,NaN,Yes,NaN,Yes,Yes,Yes,100.00%,100,2023-09-23,applied
39,84,650f1454cb796e001d5df4b3,Abu Bakar Waheed,2023-09-23,NaN,Not applied,NaN,NaN,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.00%,0,2023-09-23,Not applied

In [27]:
# df_new.to_csv("FILES/Applicants_new.csv", index = False)

In [28]:
# df_old = pd.read_csv("FILES/Applicants_old.csv")
# df_new = pd.read_csv("FILES/Applicants_new.csv")

In [29]:
""""
updated_records = []

for index, row_old in df_old.iterrows():
    _id = row_old["_id"]

    if _id in df_new["_id"].values:
        row_new = df_new[df_new["_id"] == _id].iloc[0]
        
#         # Extract desired columns from df_new
        profile_completion_percent = row_new["Profile Completion %"]
        profile_completion = row_new["ProfileCompletion"]
        
#         # Update the relevant columns in the old row
        row_old["Profile Completion %"] = profile_completion_percent
        row_old["ProfileCompletion"] = profile_completion
    
    # Append the updated row to the list
    updated_records.append(row_old)

updated_df = pd.concat(updated_records, axis=1).T

# Export updated dataframe as CSV
updated_df.to_csv("FILES/Applicants_old.csv", index=False)
updated_df
"""

'"\nupdated_records = []\n\nfor index, row_old in df_old.iterrows():\n    _id = row_old["_id"]\n\n    if _id in df_new["_id"].values:\n        row_new = df_new[df_new["_id"] == _id].iloc[0]\n        \n#         # Extract desired columns from df_new\n        profile_completion_percent = row_new["Profile Completion %"]\n        profile_completion = row_new["ProfileCompletion"]\n        \n#         # Update the relevant columns in the old row\n        row_old["Profile Completion %"] = profile_completion_percent\n        row_old["ProfileCompletion"] = profile_completion\n    \n    # Append the updated row to the list\n    updated_records.append(row_old)\n\nupdated_df = pd.concat(updated_records, axis=1).T\n\n# Export updated dataframe as CSV\nupdated_df.to_csv("FILES/Applicants_old.csv", index=False)\nupdated_df\n'