In [10]:
import gspread
import pandas as pd
import openpyxl
import datetime

In [11]:
gc = gspread.oauth()
sh = gc.open("Associate: Ashar Saleem")
print(sh)
spreadsheet_data = gc.export(sh.id,gspread.utils.ExportFormat.CSV)
print("Excel created")

FILE_NAME = "FILES/Dashboard.csv"
SHEET = ""
FULLNAME = "Ashar Saleem"

# Write the binary data to a file
with open(FILE_NAME, 'wb') as file:
    file.write(spreadsheet_data)

<Spreadsheet 'Associate: Ashar Saleem' id:1ASWbNa3Yd0q4vac-0_i3vupPcfgVOMUM5hAKOHjgHeY>
Excel created

In [12]:
df_new = pd.read_csv("FILES/Dashboard.csv", parse_dates=['signup_date'])
print(df_new.shape)
df_new = df_new.drop_duplicates(keep= "first", subset = "_id")
print(df_new.shape)
df_new.head()

(344, 37)
(304, 37)

,_id,full_name,signup_date,referrer_name,application,title,name,onboardingstep,aboutme1,profileheadline,...,gender,photo,phone_number,languages,secondaryemail,whatsappnumber,interested_in,is_visa_required,salary_range,Profile Completion %
0,649962b7508a29001dc2a6bf,Syed Usama Sohail,2023-06-26,NaN,applied,People Intern,Qureos,13.0,NaN,NaN,...,Yes,NaN,Yes,NaN,NaN,NaN,NaN,Yes,Yes,58.33%
5,64a297db1b4a4b001d1f7b45,Lamia Boudjellel,2023-07-03,NaN,applied,Sales Agent,Empire Heights Properties,9.0,NaN,NaN,...,Yes,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Yes,41.67%
6,64ad92b35dae83001d7665e2,Arun Chachan,2023-07-11,NaN,Not applied,NaN,NaN,13.0,Yes,NaN,...,Yes,Yes,Yes,NaN,NaN,NaN,NaN,Yes,Yes,83.33%
7,64e64ed2116795001dbba6b5,Abdallah Al Harthi,2023-08-23,NaN,applied,Business Development Executive,Dhofar Global Tr Co LLC,9.0,Yes,NaN,...,NaN,NaN,Yes,NaN,NaN,NaN,Yes,Yes,Yes,100.00%
8,64a28cce38dc80001d3baf73,Suleman Rajput,2023-07-03,NaN,applied,UI/UX Designer,Venture Republic,13.0,Yes,NaN,...,Yes,Yes,Yes,NaN,Yes,Yes,NaN,Yes,NaN,75.00%

In [13]:
df_new['Current_Time'] = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
df_new['Remaining Count'] = 3

df_new['ProfileCompletion'] = pd.to_numeric(df_new['Profile Completion %'].str.split('%', expand=True)[0])
df_new = df_new.sort_values(by=['signup_date'], axis=0, ascending=False)

### How many new applicants in one week span

In [14]:
today = datetime.date.today()
PreviousMonday = today - datetime.timedelta(days=today.weekday(), weeks=1)

print(str(PreviousMonday))
PreviousMonday = "2023-09-01"
print(df_new[df_new['signup_date'] >= str(PreviousMonday)].shape)
# df_new[df_new['signup_date'] >= "2023-07-26" ]
# df_new[ (df_new['signup_date'] >= "2023-07-1") & (df_new['ProfileCompletion'] == 100)] .shape
df_new.loc[:,'signup_date_same'] = df_new['signup_date']
df_new.loc[:,'application_same'] = df_new['application']
df_new = df_new[df_new['signup_date'] >= str(PreviousMonday)]

2023-09-18

(76, 40)

In [15]:

df_new2 = df_new[df_new['ProfileCompletion'] == 100].reset_index(drop=True)
# df_new2 = df_new[df_new['onboardingstep'] == 13].reset_index(drop=True)
# df_new2 = df_new[df_new['application'] == 'applied'].reset_index(drop=True)
# df_new2 = df_new[(df_new['ProfileCompletion'] == 100)  & (df_new['application'] == 'applied')] .reset_index(drop=True)
print(len(df_new2)-3)
df_new.reset_index()[:40]

44

,index,_id,full_name,signup_date,referrer_name,application,title,name,onboardingstep,aboutme1,...,whatsappnumber,interested_in,is_visa_required,salary_range,Profile Completion %,Current_Time,Remaining Count,ProfileCompletion,signup_date_same,application_same
0,148,6518db0fc02bbc001dca4a58,Shubham Singh,2023-10-01,NaN,applied,Business Development Executive,Dhofar Global Tr Co LLC,9.0,Yes,...,Yes,NaN,NaN,NaN,58.33%,2023-10-01 15:16:49,3,58.33,2023-10-01,applied
1,223,6518ef9c81a4ad001d5f44ca,Ranotosh Ghosh,2023-10-01,NaN,applied,Business Development Executive,Dhofar Global Tr Co LLC,9.0,Yes,...,Yes,Yes,Yes,Yes,100.00%,2023-10-01 15:16:49,3,100.00,2023-10-01,applied
2,209,65185aaee34bdb001d3adb5a,Duha Saeed,2023-09-30,NaN,Not applied,NaN,NaN,9.0,NaN,...,NaN,NaN,NaN,NaN,50.00%,2023-10-01 15:16:49,3,50.00,2023-09-30,Not applied
3,26,651854bae2b036001ee3e874,Ahmed Abdelrazik,2023-09-30,NaN,applied,Business Development Executive,Dhofar Global Tr Co LLC,9.0,NaN,...,Yes,NaN,NaN,NaN,41.67%,2023-10-01 15:16:49,3,41.67,2023-09-30,applied
4,161,6518558d4f56e3001d0a2e99,Hassan Algain,2023-09-30,NaN,applied,Marketing Manager,Atari,9.0,NaN,...,Yes,NaN,NaN,NaN,50.00%,2023-10-01 15:16:49,3,50.00,2023-09-30,applied
5,170,6518623db1da38001dcd8fb7,Yara Mhmd,2023-09-30,NaN,Not applied,NaN,NaN,9.0,NaN,...,Yes,NaN,NaN,NaN,41.67%,2023-10-01 15:16:49,3,41.67,2023-09-30,Not applied
6,122,651854b72dbd11001d2bb3a5,Georjedine Jeanlouis,2023-09-30,NaN,Not applied,NaN,NaN,5.0,NaN,...,NaN,NaN,NaN,NaN,25.00%,2023-10-01 15:16:49,3,25.00,2023-09-30,Not applied
7,184,651857522b7065001ddaca54,Mehsab Ali e,2023-09-30,NaN,applied,Accountant,Alzayani Investments,9.0,NaN,...,Yes,NaN,NaN,NaN,50.00%,2023-10-01 15:16:49,3,50.00,2023-09-30,applied
8,136,65185732519db2001d548bd9,Eslam Morsy,2023-09-30,NaN,Not applied,NaN,NaN,9.0,NaN,...,NaN,NaN,NaN,NaN,50.00%,2023-10-01 15:16:49,3,50.00,2023-09-30,Not applied
9,259,65185c2b2dbd11001d2bb56d,Eslam Mohamed,2023-09-30,NaN,Not applied,NaN,NaN,9.0,NaN,...,Yes,NaN,NaN,NaN,41.67%,2023-10-01 15:16:49,3,41.67,2023-09-30,Not applied
10,258,65186692e34bdb001d3aee4e,Ashly Sara Koshy,2023-09-30,NaN,Not applied,NaN,NaN,9.0,NaN,...,NaN,NaN,NaN,Yes,50.00%,2023-10-01 15:16:49,3,50.00,2023-09-30,Not applied
11,257,651885bf3689f2001d7c95c4,Sayed hassan sayed Ahmed,2023-09-30,NaN,Not applied,NaN,NaN,7.0,NaN,...,Yes,NaN,NaN,Yes,50.00%,2023-10-01 15:16:49,3,50.00,2023-09-30,Not applied
12,318,651873621f6eb0001d94d1b2,Yehya Asal,2023-09-30,NaN,applied,Business Development Executive,Dhofar Global Tr Co LLC,9.0,NaN,...,NaN,NaN,NaN,NaN,50.00%,2023-10-01 15:16:49,3,50.00,2023-09-30,applied
13,270,6513ecba5b38f7001d6c200d,Mohammed Bayaz,2023-09-27,NaN,applied,Interior Design Draftsman,Qureos Recruitment,9.0,NaN,...,Yes,NaN,NaN,Yes,58.33%,2023-10-01 15:16:49,3,58.33,2023-09-27,applied
14,99,651274bbef73aa001da534d3,Mohammad Bashar,2023-09-26,NaN,Not applied,NaN,NaN,2.0,NaN,...,NaN,NaN,NaN,NaN,0.00%,2023-10-01 15:16:49,3,0.00,2023-09-26,Not applied
15,9,6512ca5f881c9b001d4fec37,Safvan Vt,2023-09-26,NaN,applied,Interior Design Draftsman,Qureos Recruitment,9.0,Yes,...,Yes,Yes,Yes,Yes,100.00%,2023-10-01 15:16:49,3,100.00,2023-09-26,applied
16,65,6511def666c03e001dbe2f73,Kartiksingh Hushare,2023-09-25,NaN,Not applied,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,0.00%,2023-10-01 15:16:49,3,0.00,2023-09-25,Not applied
17,193,65111816ebc35b001d6a123a,shafiq mohammed,2023-09-25,NaN,applied,Procurement Assistant,ADEKA AL OTAIBA MIDDLE EAST,9.0,Yes,...,NaN,Yes,Yes,Yes,100.00%,2023-10-01 15:16:49,3,100.00,2023-09-25,applied
18,97,6511d846e2772d001de51744,Alex Varghese,2023-09-25,NaN,applied,Procurement Assistant,ADEKA AL OTAIBA MIDDLE EAST,9.0,Yes,...,Yes,NaN,NaN,Yes,66.67%,2023-10-01 15:16:49,3,66.67,2023-09-25,applied
19,332,651111f79348f0001d78c621,AMALNADH NJ,2023-09-25,NaN,applied,Interior Design Draftsman,Qureos Recruitment,9.0,Yes,...,Yes,NaN,NaN,NaN,58.33%,2023-10-01 15:16:49,3,58.33,2023-09-25,applied
20,79,6511e08a4786f9001d29fc15,Edward Jerameel Martin,2023-09-25,NaN,applied,Procurement Assistant,ADEKA AL OTAIBA MIDDLE EAST,9.0,Yes,...,NaN,NaN,NaN,Yes,66.67%,2023-10-01 15:16:49,3,66.67,2023-09-25,applied
21,321,650fcf78781892001ddc3d2b,nabil sayyed,2023-09-24,NaN,applied,Interior Design Draftsman,Qureos Recruitment,9.0,Yes,...,NaN,Yes,Yes,Yes,100.00%,2023-10-01 15:16:49,3,100.00,2023-09-24,applied
22,73,650fad23b9e90b001dbf9a0f,Muhammed Shafi,2023-09-24,NaN,Not applied,NaN,NaN,2.0,NaN,...,NaN,NaN,NaN,NaN,0.00%,2023-10-01 15:16:49,3,0.00,2023-09-24,Not applied
23,214,650ff6303c8e50001c2005a8,Zawar Amin khan,2023-09-24,NaN,applied,Procurement Assistant,ADEKA AL OTAIBA MIDDLE EAST,9.0,Yes,...,Yes,Yes,Yes,Yes,100.00%,2023-10-01 15:16:49,3,100.00,2023-09-24,applied
24,134,65103b5723114b001de54884,shahbaz akhter,2023-09-24,NaN,applied,Interior Design Draftsman,Qureos Recruitment,9.0,Yes,...,NaN,Yes,Yes,Yes,100.00%,2023-10-01 15:16:49,3,100.00,2023-09-24,applied
25,18,650fef4ddc22bd001dee27ce,Md. Saiful islam Ropam,2023-09-24,NaN,Not applied,NaN,NaN,9.0,Yes,...,Yes,Yes,Yes,Yes,100.00%,2023-10-01 15:16:49,3,100.00,2023-09-24,Not applied
26,192,650fef799348f0001d784247,Syamlal Swarnappan,2023-09-24,NaN,applied,Procurement Assistant,ADEKA AL OTAIBA MIDDLE EAST,9.0,Yes,...,Yes,Yes,Yes,Yes,100.00%,2023-10-01 15:16:49,3,100.00,2023-09-24,applied
27,123,650f0913cb796e001d5defc4,bino benny,2023-09-23,NaN,applied,Procurement Assistant,ADEKA AL OTAIBA MIDDLE EAST,9.0,Yes,...,NaN,Yes,Yes,Yes,100.00%,2023-10-01 15:16:49,3,100.00,2023-09-23,applied
28,334,650f3001290fef001d21d2c8,Charinette Padolina,2023-09-23,NaN,applied,Procurement Assistant,ADEKA AL OTAIBA MIDDLE EAST,9.0,Yes,...,NaN,Yes,Yes,Yes,100.00%,2023-10-01 15:16:49,3,100.00,2023-09-23,applied
29,125,650f145b9348f0001d77f41b,Jithesh.K.P Jithu,2023-09-23,NaN,Not applied,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,0.00%,2023-10-01 15:16:49,3,0.00,2023-09-23,Not applied
30,199,650f216f0acb7b001d9321ce,Kartik Hushare,2023-09-23,NaN,applied,Procurement Assistant,ADEKA AL OTAIBA MIDDLE EAST,9.0,Yes,...,Yes,Yes,Yes,Yes,100.00%,2023-10-01 15:16:49,3,100.00,2023-09-23,applied
31,191,650f05c85e8136001d98b8b6,Karren Jake Aenlle,2023-09-23,NaN,applied,Procurement Assistant,ADEKA AL OTAIBA MIDDLE EAST,9.0,Yes,...,Yes,Yes,Yes,Yes,100.00%,2023-10-01 15:16:49,3,100.00,2023-09-23,applied
32,176,650f0237dc22bd001ded92dc,ali akbar,2023-09-23,NaN,Not applied,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.00%,2023-10-01 15:16:49,3,0.00,2023-09-23,Not applied
33,74,650f103b9348f0001d77f24e,Rashid Ali,2023-09-23,NaN,applied,Procurement Assistant,ADEKA AL OTAIBA MIDDLE EAST,9.0,Yes,...,Yes,Yes,Yes,Yes,100.00%,2023-10-01 15:16:49,3,100.00,2023-09-23,applied
34,238,650f11c4ebc35b001d693ade,subin balan,2023-09-23,NaN,applied,Interior Design Draftsman,Qureos Recruitment,9.0,Yes,...,NaN,Yes,Yes,Yes,100.00%,2023-10-01 15:16:49,3,100.00,2023-09-23,applied
35,78,650f1454cb796e001d5df4b3,Abu Bakar Waheed,2023-09-23,NaN,Not applied,NaN,NaN,2.0,NaN,...,NaN,NaN,NaN,NaN,0.00%,2023-10-01 15:16:49,3,0.00,2023-09-23,Not applied
36,291,650f2636a5d55e001d5b51fd,Arun Raghavan,2023-09-23,NaN,Not applied,NaN,NaN,7.0,NaN,...,NaN,NaN,NaN,NaN,33.33%,2023-10-01 15:16:49,3,33.33,2023-09-23,Not applied
37,295,650f14b8290fef001d21a015,John Robert Susi,2023-09-23,NaN,applied,Interior Design Draftsman,Qureos Recruitment,9.0,Yes,...,Yes,Yes,Yes,Yes,100.00%,2023-10-01 15:16:49,3,100.00,2023-09-23,applied
38,77,650f0fc1135a25001da8ca36,Rehab Tigani,2023-09-23,NaN,applied,Interior Design Draftsman,Qureos Recruitment,9.0,Yes,...,NaN,Yes,Yes,Yes,100.00%,2023-10-01 15:16:49,3,100.00,2023-09-23,applied
39,177,650597facf57b8001d761f8b,Gloria Koima,2023-09-16,NaN,applied,Chief of Staff,Terrafirma Human Resources Consultancies Co. LLC,9.0,Yes,...,Yes,Yes,Yes,Yes,100.00%,2023-10-01 15:16:49,3,100.00,2023-09-16,applied

In [16]:
# df_new.to_csv("FILES/Applicants_new.csv", index = False)

In [17]:
# df_old = pd.read_csv("FILES/Applicants_old.csv")
# df_new = pd.read_csv("FILES/Applicants_new.csv")

In [18]:
""""
updated_records = []

for index, row_old in df_old.iterrows():
    _id = row_old["_id"]

    if _id in df_new["_id"].values:
        row_new = df_new[df_new["_id"] == _id].iloc[0]
        
#         # Extract desired columns from df_new
        profile_completion_percent = row_new["Profile Completion %"]
        profile_completion = row_new["ProfileCompletion"]
        
#         # Update the relevant columns in the old row
        row_old["Profile Completion %"] = profile_completion_percent
        row_old["ProfileCompletion"] = profile_completion
    
    # Append the updated row to the list
    updated_records.append(row_old)

updated_df = pd.concat(updated_records, axis=1).T

# Export updated dataframe as CSV
updated_df.to_csv("FILES/Applicants_old.csv", index=False)
updated_df
"""

'"\nupdated_records = []\n\nfor index, row_old in df_old.iterrows():\n    _id = row_old["_id"]\n\n    if _id in df_new["_id"].values:\n        row_new = df_new[df_new["_id"] == _id].iloc[0]\n        \n#         # Extract desired columns from df_new\n        profile_completion_percent = row_new["Profile Completion %"]\n        profile_completion = row_new["ProfileCompletion"]\n        \n#         # Update the relevant columns in the old row\n        row_old["Profile Completion %"] = profile_completion_percent\n        row_old["ProfileCompletion"] = profile_completion\n    \n    # Append the updated row to the list\n    updated_records.append(row_old)\n\nupdated_df = pd.concat(updated_records, axis=1).T\n\n# Export updated dataframe as CSV\nupdated_df.to_csv("FILES/Applicants_old.csv", index=False)\nupdated_df\n'