In [1]:
import gspread
import pandas as pd
import openpyxl
import datetime

In [2]:
gc = gspread.oauth()
sh = gc.open("Associate: Ashar Saleem")
print(sh)
spreadsheet_data = gc.export(sh.id,gspread.utils.ExportFormat.CSV)
print("Excel created")

FILE_NAME = "FILES/Dashboard.csv"
SHEET = ""
FULLNAME = "Ashar Saleem"

# Write the binary data to a file
with open(FILE_NAME, 'wb') as file:
    file.write(spreadsheet_data)

<Spreadsheet 'Associate: Ashar Saleem' id:1ASWbNa3Yd0q4vac-0_i3vupPcfgVOMUM5hAKOHjgHeY>
Excel created

In [3]:
df_new = pd.read_csv("FILES/Dashboard.csv", parse_dates=['signup_date'])
print(df_new.shape)
df_new = df_new.drop_duplicates(keep= "first", subset = "_id")
print(df_new.shape)
df_new.head()

(327, 37)
(291, 37)

,_id,full_name,signup_date,referrer_name,application,title,name,onboardingstep,aboutme1,profileheadline,...,gender,photo,phone_number,languages,secondaryemail,whatsappnumber,interested_in,is_visa_required,salary_range,Profile Completion %
0,64dc58f0523152001e0ee1e5,Noor ul Hassan,2023-08-16,NaN,applied,Sales Specialist,Empire Heights Properties,9.0,Yes,NaN,...,NaN,NaN,Yes,NaN,NaN,Yes,Yes,Yes,Yes,100.00%
1,649f27f61b4a4b001d086f27,Monica Bruno,2023-06-30,NaN,applied,Senior Marketing Specialist,Perfect Purity,13.0,NaN,NaN,...,Yes,Yes,Yes,NaN,Yes,NaN,NaN,Yes,Yes,58.33%
2,64f1bb15c9c8bd001dda11ad,Saba Qaisar,2023-09-01,NaN,applied,IT Coordinator,Alzayani Investments,9.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41.67%
3,64de23b3247256001d5a51ef,waqar hyder,2023-08-17,NaN,Not applied,NaN,NaN,9.0,Yes,NaN,...,NaN,NaN,Yes,NaN,Yes,Yes,Yes,Yes,Yes,100.00%
4,64dc6966862274001de427ca,fady Samy,2023-08-16,NaN,Not applied,NaN,NaN,9.0,Yes,NaN,...,NaN,NaN,Yes,NaN,NaN,NaN,Yes,Yes,Yes,100.00%

In [4]:
df_new['Current_Time'] = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
df_new['Remaining Count'] = 3

df_new['ProfileCompletion'] = pd.to_numeric(df_new['Profile Completion %'].str.split('%', expand=True)[0])
df_new = df_new.sort_values(by=['signup_date'], axis=0, ascending=False)

### How many new applicants in one week span

In [5]:
today = datetime.date.today()
PreviousMonday = today - datetime.timedelta(days=today.weekday(), weeks=1)

print(str(PreviousMonday))
PreviousMonday = "2023-09-01"
print(df_new[df_new['signup_date'] >= str(PreviousMonday)].shape)
# df_new[df_new['signup_date'] >= "2023-07-26" ]
# df_new[ (df_new['signup_date'] >= "2023-07-1") & (df_new['ProfileCompletion'] == 100)] .shape
df_new.loc[:,'signup_date_same'] = df_new['signup_date']
df_new.loc[:,'application_same'] = df_new['application']
df_new = df_new[df_new['signup_date'] >= str(PreviousMonday)]

2023-09-18
(63, 40)

In [6]:

df_new2 = df_new[df_new['ProfileCompletion'] == 100].reset_index(drop=True)
# df_new2 = df_new[df_new['onboardingstep'] == 13].reset_index(drop=True)
# df_new2 = df_new[df_new['application'] == 'applied'].reset_index(drop=True)
# df_new2 = df_new[(df_new['ProfileCompletion'] == 100)  & (df_new['application'] == 'applied')] .reset_index(drop=True)
print(len(df_new2)-3)
df_new.reset_index()[:30]

43

,index,_id,full_name,signup_date,referrer_name,application,title,name,onboardingstep,aboutme1,...,whatsappnumber,interested_in,is_visa_required,salary_range,Profile Completion %,Current_Time,Remaining Count,ProfileCompletion,signup_date_same,application_same
0,205,6513ecba5b38f7001d6c200d,Mohammed Bayaz,2023-09-27,NaN,applied,Interior Design Draftsman,Qureos Recruitment,9.0,NaN,...,Yes,NaN,NaN,Yes,58.33%,2023-09-30 22:49:30,3,58.33,2023-09-27,applied
1,185,651274bbef73aa001da534d3,Mohammad Bashar,2023-09-26,NaN,Not applied,NaN,NaN,2.0,NaN,...,NaN,NaN,NaN,NaN,0.00%,2023-09-30 22:49:30,3,0.00,2023-09-26,Not applied
2,76,6512ca5f881c9b001d4fec37,Safvan Vt,2023-09-26,NaN,applied,Interior Design Draftsman,Qureos Recruitment,9.0,Yes,...,Yes,Yes,Yes,Yes,100.00%,2023-09-30 22:49:30,3,100.00,2023-09-26,applied
3,323,65111816ebc35b001d6a123a,shafiq mohammed,2023-09-25,NaN,applied,Procurement Assistant,ADEKA AL OTAIBA MIDDLE EAST,9.0,Yes,...,NaN,Yes,Yes,Yes,100.00%,2023-09-30 22:49:30,3,100.00,2023-09-25,applied
4,114,6511d846e2772d001de51744,Alex Varghese,2023-09-25,NaN,applied,Procurement Assistant,ADEKA AL OTAIBA MIDDLE EAST,9.0,Yes,...,Yes,NaN,NaN,Yes,66.67%,2023-09-30 22:49:30,3,66.67,2023-09-25,applied
5,37,651111f79348f0001d78c621,AMALNADH NJ,2023-09-25,NaN,applied,Interior Design Draftsman,Qureos Recruitment,9.0,Yes,...,Yes,NaN,NaN,NaN,58.33%,2023-09-30 22:49:30,3,58.33,2023-09-25,applied
6,125,6511e08a4786f9001d29fc15,Edward Jerameel Martin,2023-09-25,NaN,applied,Procurement Assistant,ADEKA AL OTAIBA MIDDLE EAST,9.0,Yes,...,NaN,NaN,NaN,Yes,66.67%,2023-09-30 22:49:30,3,66.67,2023-09-25,applied
7,52,6511def666c03e001dbe2f73,Kartiksingh Hushare,2023-09-25,NaN,Not applied,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,0.00%,2023-09-30 22:49:30,3,0.00,2023-09-25,Not applied
8,287,650fad23b9e90b001dbf9a0f,Muhammed Shafi,2023-09-24,NaN,Not applied,NaN,NaN,2.0,NaN,...,NaN,NaN,NaN,NaN,0.00%,2023-09-30 22:49:30,3,0.00,2023-09-24,Not applied
9,324,650fef799348f0001d784247,Syamlal Swarnappan,2023-09-24,NaN,applied,Procurement Assistant,ADEKA AL OTAIBA MIDDLE EAST,9.0,Yes,...,Yes,Yes,Yes,Yes,100.00%,2023-09-30 22:49:30,3,100.00,2023-09-24,applied
10,71,65103b5723114b001de54884,shahbaz akhter,2023-09-24,NaN,applied,Interior Design Draftsman,Qureos Recruitment,9.0,Yes,...,NaN,Yes,Yes,Yes,100.00%,2023-09-30 22:49:30,3,100.00,2023-09-24,applied
11,182,650ff6303c8e50001c2005a8,Zawar Amin khan,2023-09-24,NaN,applied,Procurement Assistant,ADEKA AL OTAIBA MIDDLE EAST,9.0,Yes,...,Yes,Yes,Yes,Yes,100.00%,2023-09-30 22:49:30,3,100.00,2023-09-24,applied
12,137,650fef4ddc22bd001dee27ce,Md. Saiful islam Ropam,2023-09-24,NaN,Not applied,NaN,NaN,9.0,Yes,...,Yes,Yes,Yes,Yes,100.00%,2023-09-30 22:49:30,3,100.00,2023-09-24,Not applied
13,150,650fcf78781892001ddc3d2b,nabil sayyed,2023-09-24,NaN,applied,Interior Design Draftsman,Qureos Recruitment,9.0,Yes,...,NaN,Yes,Yes,Yes,100.00%,2023-09-30 22:49:30,3,100.00,2023-09-24,applied
14,261,650f145b9348f0001d77f41b,Jithesh.K.P Jithu,2023-09-23,NaN,Not applied,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,0.00%,2023-09-30 22:49:30,3,0.00,2023-09-23,Not applied
15,45,650f216f0acb7b001d9321ce,Kartik Hushare,2023-09-23,NaN,applied,Procurement Assistant,ADEKA AL OTAIBA MIDDLE EAST,9.0,Yes,...,Yes,Yes,Yes,Yes,100.00%,2023-09-30 22:49:30,3,100.00,2023-09-23,applied
16,128,650f1454cb796e001d5df4b3,Abu Bakar Waheed,2023-09-23,NaN,Not applied,NaN,NaN,2.0,NaN,...,NaN,NaN,NaN,NaN,0.00%,2023-09-30 22:49:30,3,0.00,2023-09-23,Not applied
17,245,650f11c4ebc35b001d693ade,subin balan,2023-09-23,NaN,applied,Interior Design Draftsman,Qureos Recruitment,9.0,Yes,...,NaN,Yes,Yes,Yes,100.00%,2023-09-30 22:49:30,3,100.00,2023-09-23,applied
18,93,650f2636a5d55e001d5b51fd,Arun Raghavan,2023-09-23,NaN,Not applied,NaN,NaN,7.0,NaN,...,NaN,NaN,NaN,NaN,33.33%,2023-09-30 22:49:30,3,33.33,2023-09-23,Not applied
19,127,650f0fc1135a25001da8ca36,Rehab Tigani,2023-09-23,NaN,applied,Interior Design Draftsman,Qureos Recruitment,9.0,Yes,...,NaN,Yes,Yes,Yes,100.00%,2023-09-30 22:49:30,3,100.00,2023-09-23,applied
20,147,650f3001290fef001d21d2c8,Charinette Padolina,2023-09-23,NaN,applied,Procurement Assistant,ADEKA AL OTAIBA MIDDLE EAST,9.0,Yes,...,NaN,Yes,Yes,Yes,100.00%,2023-09-30 22:49:30,3,100.00,2023-09-23,applied
21,219,650f14b8290fef001d21a015,John Robert Susi,2023-09-23,NaN,applied,Interior Design Draftsman,Qureos Recruitment,9.0,Yes,...,Yes,Yes,Yes,Yes,100.00%,2023-09-30 22:49:30,3,100.00,2023-09-23,applied
22,16,650f0913cb796e001d5defc4,bino benny,2023-09-23,NaN,applied,Procurement Assistant,ADEKA AL OTAIBA MIDDLE EAST,9.0,Yes,...,NaN,Yes,Yes,Yes,100.00%,2023-09-30 22:49:30,3,100.00,2023-09-23,applied
23,288,650f103b9348f0001d77f24e,Rashid Ali,2023-09-23,NaN,applied,Procurement Assistant,ADEKA AL OTAIBA MIDDLE EAST,9.0,Yes,...,Yes,Yes,Yes,Yes,100.00%,2023-09-30 22:49:30,3,100.00,2023-09-23,applied
24,307,650f0237dc22bd001ded92dc,ali akbar,2023-09-23,NaN,Not applied,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.00%,2023-09-30 22:49:30,3,0.00,2023-09-23,Not applied
25,40,650f05c85e8136001d98b8b6,Karren Jake Aenlle,2023-09-23,NaN,applied,Procurement Assistant,ADEKA AL OTAIBA MIDDLE EAST,9.0,Yes,...,Yes,Yes,Yes,Yes,100.00%,2023-09-30 22:49:30,3,100.00,2023-09-23,applied
26,251,650597facf57b8001d761f8b,Gloria Koima,2023-09-16,NaN,applied,Chief of Staff,Terrafirma Human Resources Consultancies Co. LLC,9.0,Yes,...,Yes,Yes,Yes,Yes,100.00%,2023-09-30 22:49:30,3,100.00,2023-09-16,applied
27,253,65057a1412b009001ddda45a,Sayeeduddin Mohammed,2023-09-16,NaN,Not applied,NaN,NaN,1.0,NaN,...,Yes,NaN,NaN,NaN,50.00%,2023-09-30 22:49:30,3,50.00,2023-09-16,Not applied
28,50,650580c4bf9692001d884645,Amitesh Rawat,2023-09-16,NaN,applied,Chief of Staff,Terrafirma Human Resources Consultancies Co. LLC,9.0,Yes,...,Yes,Yes,Yes,Yes,100.00%,2023-09-30 22:49:30,3,100.00,2023-09-16,applied
29,48,65008b7e1861b6001d6cb41c,Zohal Ahmad Shah,2023-09-12,NaN,Not applied,NaN,NaN,2.0,NaN,...,NaN,NaN,NaN,NaN,0.00%,2023-09-30 22:49:30,3,0.00,2023-09-12,Not applied

In [7]:
# df_new.to_csv("FILES/Applicants_new.csv", index = False)

In [8]:
# df_old = pd.read_csv("FILES/Applicants_old.csv")
# df_new = pd.read_csv("FILES/Applicants_new.csv")

In [9]:
""""
updated_records = []

for index, row_old in df_old.iterrows():
    _id = row_old["_id"]

    if _id in df_new["_id"].values:
        row_new = df_new[df_new["_id"] == _id].iloc[0]
        
#         # Extract desired columns from df_new
        profile_completion_percent = row_new["Profile Completion %"]
        profile_completion = row_new["ProfileCompletion"]
        
#         # Update the relevant columns in the old row
        row_old["Profile Completion %"] = profile_completion_percent
        row_old["ProfileCompletion"] = profile_completion
    
    # Append the updated row to the list
    updated_records.append(row_old)

updated_df = pd.concat(updated_records, axis=1).T

# Export updated dataframe as CSV
updated_df.to_csv("FILES/Applicants_old.csv", index=False)
updated_df
"""

'"\nupdated_records = []\n\nfor index, row_old in df_old.iterrows():\n    _id = row_old["_id"]\n\n    if _id in df_new["_id"].values:\n        row_new = df_new[df_new["_id"] == _id].iloc[0]\n        \n#         # Extract desired columns from df_new\n        profile_completion_percent = row_new["Profile Completion %"]\n        profile_completion = row_new["ProfileCompletion"]\n        \n#         # Update the relevant columns in the old row\n        row_old["Profile Completion %"] = profile_completion_percent\n        row_old["ProfileCompletion"] = profile_completion\n    \n    # Append the updated row to the list\n    updated_records.append(row_old)\n\nupdated_df = pd.concat(updated_records, axis=1).T\n\n# Export updated dataframe as CSV\nupdated_df.to_csv("FILES/Applicants_old.csv", index=False)\nupdated_df\n'